name: User-Story
description: File a User Story.
title: "User Story Name"
labels: ["user story", "green"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:
  - type: textarea
    id: user-story
    attributes:
      label: User Story
      value: "Write here Description"
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      value: "Write here Acceptance Criteria"
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: What is Priority ?
      options:
        - High (Default)
        - Medium
        - Low
      default: 0
    validations:
      required: true

  - type: textarea
    id: database-schema
    attributes:
      label: Database Schema
      value: "Write here Database Schema"
    validations:
      required: false

